- hosts: localhost
  vars:
    ssh_key_name: "{{ lookup('env', 'SSH_KEY_NAME', default='id_ed25519') }}"
    source_key: "/usr/local/bin/.ssh/{{ ssh_key_name }}"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/{{ ssh_key_name }}"
  
  pre_tasks:
    - name: Update cache
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - nvim
        # - zsh
        # - ssh
        # - dotfiles
        # - stow
  
  tasks:
    # - include_tasks: local-tasks/zsh.yml
    # - include_tasks: local-tasks/ssh.yml
    # - include_tasks: local-tasks/dotfiles.yml
    # - include_tasks: local-tasks/stow.yml
    - include_tasks: local-tasks/nvim.yml
