- hosts: localhost
  vars:
    ssh_keys:
      - id_ed25519_personal
      - id_ed25519_work
    ssh_source_dir: "{{ playbook_dir }}/.ssh"
    ssh_dest_dir: "{{ lookup('env', 'HOME') }}/.ssh"
    ansible_become_method: sudo
    ansible_sudo_flags: "-n"  
  pre_tasks:
    - name: Update cache
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
          - nvim
          - zsh
          - ssh
          - dotfiles
          - stow
          - core-programs
          - docker
          - ghostty
          - go
          - node
          - floorp
          - claude-code
          - spotify
          - slack
          - obsidian

  tasks:
    - import_tasks: local-tasks/ssh.yml
    - import_tasks: local-tasks/zsh.yml
    - import_tasks: local-tasks/dotfiles.yml
    - import_tasks: local-tasks/core-programs.yml
    - import_tasks: local-tasks/stow.yml
    - import_tasks: local-tasks/nvim.yml
    - import_tasks: local-tasks/go.yml
    - import_tasks: local-tasks/node.yml
    - import_tasks: local-tasks/docker.yml
    - import_tasks: local-tasks/ghostty.yml
    - import_tasks: local-tasks/floorp-install.yml
    - import_tasks: local-tasks/claude-code.yml
    - import_tasks: local-tasks/spotify.yml
    - import_tasks: local-tasks/slack.yml
    - import_tasks: local-tasks/obsidian.yml
